[general_settings]
async_workers = 4
blocking_workers = 2
stack_size = 2048

[network_settings]
ip = [127,0,0,1]
port = 25565

[world_settings]
default = "lobby"

  [[world_settings.worlds]]
  name = "lobby"
  file_name = "lobby"
  generator = "superflat"

  [[world_settings.worlds]]
  name = "nether"
  file_name = "nether"
  generator = "nether"

  [[world_settings.worlds]]
  name = "end"
  file_name = "end"
  generator = "end"