[package]
name = "sample_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srvr-sysplugin = {path = "../srvr-sysplugin", version = "*"}

[lib]
name = "sample_plugin"
type = "dlib"