[package]
name = "srvr-sysworld"
version = "0.1.0"
edition = "2021"

[features]
default = ["worldgen", "world_gen_api"]
world_gen_api = []
worldgen = []

[dependencies]
serde = {version="*", features=['derive']}
thin_trait_object = "1"
toml = "*"
libloading = "*"
log = "*"