[package]
name = "srvr-sysworld"
version = "0.1.0"
edition = "2021"

[features]
default = ["world_builder"]
world_builder = []
worldgen = []

[dependencies]
serde = {version="*", features=['derive']}
thin_trait_object = "1"
toml = "*"
libloading = "*"
log = "*"