[package]
name = "srvr-sysworldgen"
version = "0.1.0"
edition = "2021"

[features]
default = ["world_builder"]
world_builder = []
worldgen = []

[dependencies]
serde = {version="*", features=['derive']}
toml = "*"
libloading = "*"
log = "*"